[package]
name = "spotify_cro_playlist_creator"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.16.0"
async-stream = "0.3.6"
axum = "0.8.9"
axum-extra = { version = "0.12.6", features = ["cookie", "cookie-key-expansion", "cookie-private"] }
dotenvy = "0.15.7"
futures = "0.3.32"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
rspotify = { version = "0.14", features = ["cli", "client-reqwest", "reqwest-rustls-tls"], default-features = false }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
uuid = { version = "1.23.4", features = ["v4"] }
