[package]
name = "spotify_cro_playlist_creator"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
rspotify = { version = "0.14.0", features = ["cli"] }
serde = "1.0.217"
serde_json = "1.0.135"
tokio = { version = "1.43.0", features = ["full"] }
